name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: plate-demux
        environment-file: envs/plate-demux.yaml

    - name: Activate conda environment
      run: |
        conda init bash
        source ~/.bashrc
        source activate snakemake
        conda info
        conda list

    - name: Demultiplex example files
      run: python plate-demux.py -R1 test-data/mixed-samples-R1.fastq.gz -R2 test-data/mixed-samples-R2.fastq.gz -c config.txt -o output-data --verbose
